buffer_size: 2
directory_path: ../practicos-rag/data/usa
evaluation: false
file_path: ../practicos-rag/data/usa/CFR-2024-vol8.pdf
max_previous_chunks: 400
model: gpt-3.5-turbo
model_name: sentence-transformers/paraphrase-MiniLM-L6-v2
num_samples: 2
openai_api_key: ${OPENAI_API_KEY}
rag: naive
show_chunks: 3
temperature: 0.7
threshold: 0.3
use_existing_questions: True
